// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Tx-Parser API
//
//	<b>Description of Parser-interface API-methods.</b>
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /
//	Version: 1.0.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
