// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "\u003cb\u003eDescription of Parser-interface API-methods.\u003c/b\u003e",
    "title": "Tx-Parser API",
    "version": "1.0.0"
  },
  "paths": {
    "/v1/tx-parser/getTransactions": {
      "get": {
        "tags": [
          "Parser interface"
        ],
        "summary": "List of inbound or outbound transactions for an address",
        "operationId": "txParser_getTransactions",
        "parameters": [
          {
            "type": "string",
            "format": "string",
            "description": "20 Bytes - Contract address",
            "name": "address",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "schema": {
              "type": "object",
              "properties": {
                "transactions": {
                  "description": "Transactions list",
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "blockHash": {
                        "description": "32 Bytes - hash of the block where this transaction was in. null when its pending.",
                        "type": "string",
                        "format": "string"
                      },
                      "blockNumber": {
                        "description": "block number where this transaction was in. null when its pending.",
                        "type": "string",
                        "format": "string"
                      },
                      "from": {
                        "description": "20 Bytes - address of the sender.",
                        "type": "string",
                        "format": "string"
                      },
                      "gas": {
                        "description": "gas provided by the sender.",
                        "type": "string",
                        "format": "string"
                      },
                      "gasPrice": {
                        "description": "gas price provided by the sender in Wei.",
                        "type": "string",
                        "format": "string"
                      },
                      "hash": {
                        "description": "32 Bytes - hash of the transaction.",
                        "type": "string",
                        "format": "string"
                      },
                      "input": {
                        "description": "the data send along with the transaction.",
                        "type": "string",
                        "format": "string"
                      },
                      "nonce": {
                        "description": "the number of transactions made by the sender prior to this one.",
                        "type": "string",
                        "format": "string"
                      },
                      "r": {
                        "description": "ECDSA signature r",
                        "type": "string",
                        "format": "string"
                      },
                      "s": {
                        "description": "ECDSA signature s",
                        "type": "string",
                        "format": "string"
                      },
                      "to": {
                        "description": "20 Bytes - address of the receiver. null when its a contract creation transaction.",
                        "type": "string",
                        "format": "string"
                      },
                      "transactionIndex": {
                        "description": "integer of the transactions index position in the block. null when its pending.",
                        "type": "string",
                        "format": "string"
                      },
                      "v": {
                        "description": "ECDSA recovery id",
                        "type": "string",
                        "format": "string"
                      },
                      "value": {
                        "description": "value transferred in Wei.",
                        "type": "string",
                        "format": "string"
                      }
                    }
                  }
                }
              }
            }
          },
          "default": {
            "description": "Unsuccessful response",
            "schema": {
              "$ref": "#/definitions/errorResponse"
            }
          }
        }
      }
    },
    "/v1/tx-parser/subscribe": {
      "post": {
        "tags": [
          "Parser interface"
        ],
        "summary": "Add address to observer",
        "operationId": "txParser_subscribe",
        "parameters": [
          {
            "type": "string",
            "format": "string",
            "description": "20 Bytes - Contract address",
            "name": "address",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "schema": {
              "type": "object",
              "properties": {
                "success": {
                  "type": "string",
                  "format": "boolean"
                }
              }
            }
          },
          "default": {
            "description": "Unsuccessful response",
            "schema": {
              "$ref": "#/definitions/errorResponse"
            }
          }
        }
      }
    },
    "/v1/txParser/getCurrentBlock": {
      "get": {
        "tags": [
          "Parser interface"
        ],
        "summary": "Get last parsed block",
        "operationId": "txParser_getCurrentBlock",
        "responses": {
          "200": {
            "description": "Successful response",
            "schema": {
              "type": "object",
              "properties": {
                "blockNumber": {
                  "type": "string",
                  "format": "string"
                }
              }
            }
          },
          "default": {
            "description": "Unsuccessful response",
            "schema": {
              "$ref": "#/definitions/errorResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "errorResponse": {
      "type": "object",
      "properties": {
        "error": {
          "type": "string",
          "format": "string"
        },
        "success": {
          "type": "string",
          "format": "boolean"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "\u003cb\u003eDescription of Parser-interface API-methods.\u003c/b\u003e",
    "title": "Tx-Parser API",
    "version": "1.0.0"
  },
  "paths": {
    "/v1/tx-parser/getTransactions": {
      "get": {
        "tags": [
          "Parser interface"
        ],
        "summary": "List of inbound or outbound transactions for an address",
        "operationId": "txParser_getTransactions",
        "parameters": [
          {
            "type": "string",
            "format": "string",
            "description": "20 Bytes - Contract address",
            "name": "address",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "schema": {
              "type": "object",
              "properties": {
                "transactions": {
                  "description": "Transactions list",
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/TransactionsItems0"
                  }
                }
              }
            }
          },
          "default": {
            "description": "Unsuccessful response",
            "schema": {
              "$ref": "#/definitions/errorResponse"
            }
          }
        }
      }
    },
    "/v1/tx-parser/subscribe": {
      "post": {
        "tags": [
          "Parser interface"
        ],
        "summary": "Add address to observer",
        "operationId": "txParser_subscribe",
        "parameters": [
          {
            "type": "string",
            "format": "string",
            "description": "20 Bytes - Contract address",
            "name": "address",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "schema": {
              "type": "object",
              "properties": {
                "success": {
                  "type": "string",
                  "format": "boolean"
                }
              }
            }
          },
          "default": {
            "description": "Unsuccessful response",
            "schema": {
              "$ref": "#/definitions/errorResponse"
            }
          }
        }
      }
    },
    "/v1/txParser/getCurrentBlock": {
      "get": {
        "tags": [
          "Parser interface"
        ],
        "summary": "Get last parsed block",
        "operationId": "txParser_getCurrentBlock",
        "responses": {
          "200": {
            "description": "Successful response",
            "schema": {
              "type": "object",
              "properties": {
                "blockNumber": {
                  "type": "string",
                  "format": "string"
                }
              }
            }
          },
          "default": {
            "description": "Unsuccessful response",
            "schema": {
              "$ref": "#/definitions/errorResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "TransactionsItems0": {
      "type": "object",
      "properties": {
        "blockHash": {
          "description": "32 Bytes - hash of the block where this transaction was in. null when its pending.",
          "type": "string",
          "format": "string"
        },
        "blockNumber": {
          "description": "block number where this transaction was in. null when its pending.",
          "type": "string",
          "format": "string"
        },
        "from": {
          "description": "20 Bytes - address of the sender.",
          "type": "string",
          "format": "string"
        },
        "gas": {
          "description": "gas provided by the sender.",
          "type": "string",
          "format": "string"
        },
        "gasPrice": {
          "description": "gas price provided by the sender in Wei.",
          "type": "string",
          "format": "string"
        },
        "hash": {
          "description": "32 Bytes - hash of the transaction.",
          "type": "string",
          "format": "string"
        },
        "input": {
          "description": "the data send along with the transaction.",
          "type": "string",
          "format": "string"
        },
        "nonce": {
          "description": "the number of transactions made by the sender prior to this one.",
          "type": "string",
          "format": "string"
        },
        "r": {
          "description": "ECDSA signature r",
          "type": "string",
          "format": "string"
        },
        "s": {
          "description": "ECDSA signature s",
          "type": "string",
          "format": "string"
        },
        "to": {
          "description": "20 Bytes - address of the receiver. null when its a contract creation transaction.",
          "type": "string",
          "format": "string"
        },
        "transactionIndex": {
          "description": "integer of the transactions index position in the block. null when its pending.",
          "type": "string",
          "format": "string"
        },
        "v": {
          "description": "ECDSA recovery id",
          "type": "string",
          "format": "string"
        },
        "value": {
          "description": "value transferred in Wei.",
          "type": "string",
          "format": "string"
        }
      }
    },
    "errorResponse": {
      "type": "object",
      "properties": {
        "error": {
          "type": "string",
          "format": "string"
        },
        "success": {
          "type": "string",
          "format": "boolean"
        }
      }
    }
  }
}`))
}
