// Code generated by go-swagger; DO NOT EDIT.

package parser_interface

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
)

// NewTxParserGetCurrentBlockParams creates a new TxParserGetCurrentBlockParams object
//
// There are no default values defined in the spec.
func NewTxParserGetCurrentBlockParams() TxParserGetCurrentBlockParams {

	return TxParserGetCurrentBlockParams{}
}

// TxParserGetCurrentBlockParams contains all the bound params for the tx parser get current block operation
// typically these are obtained from a http.Request
//
// swagger:parameters txParser_getCurrentBlock
type TxParserGetCurrentBlockParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewTxParserGetCurrentBlockParams() beforehand.
func (o *TxParserGetCurrentBlockParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
