// Code generated by go-swagger; DO NOT EDIT.

package parser_interface

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

/*
TxParserGetTransactionsDefault Method response

swagger:response txParserGetTransactionsDefault
*/
type TxParserGetTransactionsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *TxParserGetTransactionsDefaultBody `json:"body,omitempty"`
}

// NewTxParserGetTransactionsDefault creates TxParserGetTransactionsDefault with default headers values
func NewTxParserGetTransactionsDefault(code int) *TxParserGetTransactionsDefault {
	if code <= 0 {
		code = 500
	}

	return &TxParserGetTransactionsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the tx parser get transactions default response
func (o *TxParserGetTransactionsDefault) WithStatusCode(code int) *TxParserGetTransactionsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the tx parser get transactions default response
func (o *TxParserGetTransactionsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the tx parser get transactions default response
func (o *TxParserGetTransactionsDefault) WithPayload(payload *TxParserGetTransactionsDefaultBody) *TxParserGetTransactionsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the tx parser get transactions default response
func (o *TxParserGetTransactionsDefault) SetPayload(payload *TxParserGetTransactionsDefaultBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *TxParserGetTransactionsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
