// Code generated by go-swagger; DO NOT EDIT.

package parser_interface

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

/*
TxParserSubscribeDefault Method response

swagger:response txParserSubscribeDefault
*/
type TxParserSubscribeDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *TxParserSubscribeDefaultBody `json:"body,omitempty"`
}

// NewTxParserSubscribeDefault creates TxParserSubscribeDefault with default headers values
func NewTxParserSubscribeDefault(code int) *TxParserSubscribeDefault {
	if code <= 0 {
		code = 500
	}

	return &TxParserSubscribeDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the tx parser subscribe default response
func (o *TxParserSubscribeDefault) WithStatusCode(code int) *TxParserSubscribeDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the tx parser subscribe default response
func (o *TxParserSubscribeDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the tx parser subscribe default response
func (o *TxParserSubscribeDefault) WithPayload(payload *TxParserSubscribeDefaultBody) *TxParserSubscribeDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the tx parser subscribe default response
func (o *TxParserSubscribeDefault) SetPayload(payload *TxParserSubscribeDefaultBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *TxParserSubscribeDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
