// Code generated by go-swagger; DO NOT EDIT.

package parser_interface

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TxParserGetCurrentBlockHandlerFunc turns a function with the right signature into a tx parser get current block handler
type TxParserGetCurrentBlockHandlerFunc func(TxParserGetCurrentBlockParams) middleware.Responder

// Handle executing the request and returning a response
func (fn TxParserGetCurrentBlockHandlerFunc) Handle(params TxParserGetCurrentBlockParams) middleware.Responder {
	return fn(params)
}

// TxParserGetCurrentBlockHandler interface for that can handle valid tx parser get current block params
type TxParserGetCurrentBlockHandler interface {
	Handle(TxParserGetCurrentBlockParams) middleware.Responder
}

// NewTxParserGetCurrentBlock creates a new http.Handler for the tx parser get current block operation
func NewTxParserGetCurrentBlock(ctx *middleware.Context, handler TxParserGetCurrentBlockHandler) *TxParserGetCurrentBlock {
	return &TxParserGetCurrentBlock{Context: ctx, Handler: handler}
}

/*
	TxParserGetCurrentBlock swagger:route GET /v1/txParser/getCurrentBlock Parser interface txParserGetCurrentBlock

Get last parsed block
*/
type TxParserGetCurrentBlock struct {
	Context *middleware.Context
	Handler TxParserGetCurrentBlockHandler
}

func (o *TxParserGetCurrentBlock) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewTxParserGetCurrentBlockParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// TxParserGetCurrentBlockOKBody tx parser get current block o k body
//
// swagger:model TxParserGetCurrentBlockOKBody
type TxParserGetCurrentBlockOKBody struct {

	// block number
	BlockNumber string `json:"blockNumber,omitempty"`
}

// Validate validates this tx parser get current block o k body
func (o *TxParserGetCurrentBlockOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this tx parser get current block o k body based on context it is used
func (o *TxParserGetCurrentBlockOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *TxParserGetCurrentBlockOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *TxParserGetCurrentBlockOKBody) UnmarshalBinary(b []byte) error {
	var res TxParserGetCurrentBlockOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
